-- FlowCapital AI — run once in Supabase SQL Editor (Dashboard → SQL → New query)
-- Creates all tables and idempotent demo seed data.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_code TEXT NOT NULL UNIQUE,
    asset_name TEXT NOT NULL,
    asset_type TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    description TEXT,
    quantity NUMERIC(18, 4) NOT NULL DEFAULT 0,
    unit TEXT NOT NULL DEFAULT 'Units',
    current_location TEXT,
    lifecycle_stage TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_assets_lifecycle ON assets (lifecycle_stage);
CREATE INDEX IF NOT EXISTS idx_assets_status ON assets (status);
CREATE INDEX IF NOT EXISTS idx_assets_type ON assets (asset_type);

CREATE TABLE IF NOT EXISTS asset_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_code TEXT NOT NULL UNIQUE,
    asset_id UUID NOT NULL REFERENCES assets (id) ON DELETE RESTRICT,
    event_type TEXT NOT NULL,
    source TEXT NOT NULL,
    event_timestamp TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    severity TEXT NOT NULL DEFAULT 'info',
    status TEXT NOT NULL DEFAULT 'RECEIVED',
    idempotency_key TEXT NOT NULL UNIQUE,
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_asset ON asset_events (asset_id, event_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_events_type ON asset_events (event_type);
CREATE INDEX IF NOT EXISTS idx_events_status ON asset_events (status);

CREATE TABLE IF NOT EXISTS verifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID NOT NULL REFERENCES assets (id) ON DELETE RESTRICT,
    verification_type TEXT NOT NULL,
    source TEXT NOT NULL,
    status TEXT NOT NULL,
    confidence_score INTEGER NOT NULL CHECK (confidence_score >= 0 AND confidence_score <= 100),
    evidence_reference TEXT,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_verifications_asset ON verifications (asset_id, created_at DESC);

CREATE TABLE IF NOT EXISTS conflicts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conflict_code TEXT NOT NULL UNIQUE,
    asset_id UUID NOT NULL REFERENCES assets (id) ON DELETE RESTRICT,
    conflict_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'OPEN',
    description TEXT NOT NULL,
    expected_value TEXT,
    actual_value TEXT,
    difference_value TEXT,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    resolution_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_conflicts_asset ON conflicts (asset_id, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_conflicts_status ON conflicts (status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_conflicts_open_issue
    ON conflicts (asset_id, conflict_type)
    WHERE status IN ('OPEN', 'IN_REVIEW');

CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID REFERENCES assets (id) ON DELETE SET NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'api',
    previous_state JSONB,
    new_state JSONB,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_asset ON audit_logs (asset_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs (created_at DESC);

-- Demo seed (idempotent)

INSERT INTO assets (asset_code, asset_name, asset_type, owner_name, description, quantity, unit, current_location, lifecycle_stage, status, metadata, created_at, updated_at) VALUES ('DA-2026-001', 'Automotive Components Batch A-452', 'Automotive Manufacturing', 'Nova Manufacturing Pvt. Ltd.', 'Production is progressing but there is a 2-day production delay caused by a delayed raw-material delivery.', 18500, 'Units', 'Chennai Manufacturing Facility', 'PRODUCTION', 'ACTIVE', '{"twin":{"id":"DA-2026-001","name":"Automotive Components Batch A-452","category":"Automotive Manufacturing","owner":"Nova Manufacturing Pvt. Ltd.","buyer":"Apex Mobility Ltd.","supplier":"Precision Metals India","currentStage":"PRODUCTION","currentValue":4250000,"originalValue":5500000,"currency":"INR","quantity":18500,"unit":"Units","location":"Chennai Manufacturing Facility","status":"ACTIVE","riskLevel":"MEDIUM","riskScore":42,"financingStatus":"PARTIAL","financedAmount":2500000,"availableFinancing":730000,"availableAmount":730000,"createdAt":"2026-08-15T06:10:00.000Z","lastUpdated":"2026-08-28T07:27:00.000Z","attention":true,"situation":"Production is progressing but there is a 2-day production delay caused by a delayed raw-material delivery.","physical":{"assetId":"DA-2026-001","stage":"PRODUCTION","location":"Chennai Manufacturing Facility","quantity":18500,"unit":"Units","productionCompletion":65,"condition":"GOOD","verificationStatus":"VERIFIED","lastVerifiedAt":"2026-08-28T07:20:00.000Z"},"financial":{"assetId":"DA-2026-001","originalValue":5500000,"currentValue":4250000,"financedAmount":2500000,"availableFinancing":730000,"outstandingExposure":2500000,"currency":"INR","financingStatus":"PARTIAL"},"contractual":{"assetId":"DA-2026-001","purchaseOrderNumber":"PO-APX-2026-0842","buyer":"Apex Mobility Ltd.","supplier":"Precision Metals India","paymentTerms":"Net 60 Days","deliveryDate":"2026-09-18","contractStatus":"In force","ownershipStatus":"Supplier / work-in-progress"}}}'::jsonb, '2026-08-15T06:10:00.000Z'::timestamptz, '2026-08-28T07:27:00.000Z'::timestamptz) ON CONFLICT (asset_code) DO NOTHING;
INSERT INTO verifications (asset_id, verification_type, source, status, confidence_score, evidence_reference, verified_at, metadata) SELECT a.id, 'PHYSICAL', 'VERIFICATION', 'VERIFIED', 94, 'DA-2026-001', NOW(), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-001' AND NOT EXISTS (SELECT 1 FROM verifications v WHERE v.asset_id = a.id AND v.verification_type = 'PHYSICAL' AND v.source = 'VERIFICATION');
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, new_state, metadata) SELECT a.id, 'asset', a.id::text, 'ASSET_CREATED', 'seed', jsonb_build_object('asset_code', 'DA-2026-001'), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-001' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.asset_id = a.id AND al.action = 'ASSET_CREATED' AND al.source = 'seed');

INSERT INTO assets (asset_code, asset_name, asset_type, owner_name, description, quantity, unit, current_location, lifecycle_stage, status, metadata, created_at, updated_at) VALUES ('DA-2026-002', 'Consumer Electronics Shipment C-219', 'Consumer Electronics', 'Vertex Electronics Ltd.', 'Shipment is on schedule. Eligible for transition from finished-goods to in-transit financing.', 2400, 'Cartons', 'Chennai → Mumbai', 'IN_TRANSIT', 'ACTIVE', '{"twin":{"id":"DA-2026-002","name":"Consumer Electronics Shipment C-219","category":"Consumer Electronics","owner":"Vertex Electronics Ltd.","buyer":"Metro Retail India","supplier":"Helio Components Shenzhen","currentStage":"IN_TRANSIT","currentValue":3180000,"originalValue":3400000,"currency":"INR","quantity":2400,"unit":"Cartons","location":"Chennai \u2192 Mumbai","status":"ACTIVE","riskLevel":"LOW","riskScore":24,"financingStatus":"FINANCED","financedAmount":1800000,"availableFinancing":540000,"availableAmount":540000,"createdAt":"2026-08-08T05:00:00.000Z","lastUpdated":"2026-08-28T06:40:00.000Z","situation":"Shipment is on schedule. Eligible for transition from finished-goods to in-transit financing.","physical":{"assetId":"DA-2026-002","stage":"IN_TRANSIT","location":"NH-48 corridor, near Pune","origin":"Chennai CFS","destination":"Mumbai Bhiwandi DC","quantity":2400,"unit":"Cartons","productionCompletion":100,"condition":"GOOD","verificationStatus":"VERIFIED","lastVerifiedAt":"2026-08-28T04:15:00.000Z","shipmentStatus":"On schedule \u00b7 ETA 30 Aug"},"financial":{"assetId":"DA-2026-002","originalValue":3400000,"currentValue":3180000,"financedAmount":1800000,"availableFinancing":540000,"outstandingExposure":1800000,"currency":"INR","financingStatus":"FINANCED"},"contractual":{"assetId":"DA-2026-002","purchaseOrderNumber":"PO-MRI-2026-219","buyer":"Metro Retail India","supplier":"Helio Components Shenzhen","paymentTerms":"Net 45 Days","deliveryDate":"2026-08-30","contractStatus":"In force","ownershipStatus":"In transit \u00b7 seller until DC scan"}}}'::jsonb, '2026-08-08T05:00:00.000Z'::timestamptz, '2026-08-28T06:40:00.000Z'::timestamptz) ON CONFLICT (asset_code) DO NOTHING;
INSERT INTO verifications (asset_id, verification_type, source, status, confidence_score, evidence_reference, verified_at, metadata) SELECT a.id, 'PHYSICAL', 'VERIFICATION', 'VERIFIED', 93, 'DA-2026-002', NOW(), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-002' AND NOT EXISTS (SELECT 1 FROM verifications v WHERE v.asset_id = a.id AND v.verification_type = 'PHYSICAL' AND v.source = 'VERIFICATION');
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, new_state, metadata) SELECT a.id, 'asset', a.id::text, 'ASSET_CREATED', 'seed', jsonb_build_object('asset_code', 'DA-2026-002'), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-002' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.asset_id = a.id AND al.action = 'ASSET_CREATED' AND al.source = 'seed');

INSERT INTO assets (asset_code, asset_name, asset_type, owner_name, description, quantity, unit, current_location, lifecycle_stage, status, metadata, created_at, updated_at) VALUES ('DA-2026-003', 'Industrial Machinery Components M-778', 'Industrial Equipment', 'Titan Industrial Systems', 'A quantity mismatch was detected between production records and warehouse records.', 86, 'Assemblies', 'Pune Central Warehouse', 'WAREHOUSE', 'WATCH', '{"twin":{"id":"DA-2026-003","name":"Industrial Machinery Components M-778","category":"Industrial Equipment","owner":"Titan Industrial Systems","buyer":"Global Engineering Corp.","supplier":"ForgeWorks Pune","currentStage":"WAREHOUSE","currentValue":5620000,"originalValue":5900000,"currency":"INR","quantity":86,"unit":"Assemblies","location":"Pune Central Warehouse","status":"WATCH","riskLevel":"HIGH","riskScore":76,"financingStatus":"PENDING_REVIEW","financedAmount":3900000,"availableFinancing":210000,"availableAmount":210000,"createdAt":"2026-07-22T08:00:00.000Z","lastUpdated":"2026-08-28T05:10:00.000Z","attention":true,"situation":"A quantity mismatch was detected between production records and warehouse records.","physical":{"assetId":"DA-2026-003","stage":"WAREHOUSE","location":"Pune Central Warehouse \u00b7 Bay 12","quantity":86,"unit":"Assemblies","productionCompletion":100,"condition":"WATCH","verificationStatus":"MISMATCH","lastVerifiedAt":"2026-08-28T05:02:00.000Z"},"financial":{"assetId":"DA-2026-003","originalValue":5900000,"currentValue":5620000,"financedAmount":3900000,"availableFinancing":210000,"outstandingExposure":3900000,"currency":"INR","financingStatus":"PENDING_REVIEW"},"contractual":{"assetId":"DA-2026-003","purchaseOrderNumber":"PO-GEC-2026-778","buyer":"Global Engineering Corp.","supplier":"ForgeWorks Pune","paymentTerms":"Net 30 Days after GRN","deliveryDate":"2026-09-04","contractStatus":"Held pending reconciliation","ownershipStatus":"Warehouse receipt \u00b7 disputed quantity"}}}'::jsonb, '2026-07-22T08:00:00.000Z'::timestamptz, '2026-08-28T05:10:00.000Z'::timestamptz) ON CONFLICT (asset_code) DO NOTHING;
INSERT INTO verifications (asset_id, verification_type, source, status, confidence_score, evidence_reference, verified_at, metadata) SELECT a.id, 'PHYSICAL', 'VERIFICATION', 'FAILED', 58, 'DA-2026-003', NOW(), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-003' AND NOT EXISTS (SELECT 1 FROM verifications v WHERE v.asset_id = a.id AND v.verification_type = 'PHYSICAL' AND v.source = 'VERIFICATION');
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, new_state, metadata) SELECT a.id, 'asset', a.id::text, 'ASSET_CREATED', 'seed', jsonb_build_object('asset_code', 'DA-2026-003'), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-003' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.asset_id = a.id AND al.action = 'ASSET_CREATED' AND al.source = 'seed');

INSERT INTO assets (asset_code, asset_name, asset_type, owner_name, description, quantity, unit, current_location, lifecycle_stage, status, metadata, created_at, updated_at) VALUES ('DA-2026-004', 'Solar Panel Manufacturing Order S-341', 'Renewable Energy', 'SunGrid Technologies', 'Verified purchase order received and procurement financing opportunity identified.', 4200, 'Panels', 'PO desk · Ahmedabad', 'PURCHASE_ORDER', 'ACTIVE', '{"twin":{"id":"DA-2026-004","name":"Solar Panel Manufacturing Order S-341","category":"Renewable Energy","owner":"SunGrid Technologies","buyer":"EcoPower Projects Ltd.","supplier":"Gujarat Glass & Cell Co.","currentStage":"PURCHASE_ORDER","currentValue":7800000,"originalValue":7800000,"currency":"INR","quantity":4200,"unit":"Panels","location":"PO desk \u00b7 Ahmedabad","status":"ACTIVE","riskLevel":"LOW","riskScore":18,"financingStatus":"UNFINANCED","financedAmount":0,"availableFinancing":4680000,"availableAmount":4680000,"createdAt":"2026-08-26T09:30:00.000Z","lastUpdated":"2026-08-28T04:00:00.000Z","situation":"Verified purchase order received and procurement financing opportunity identified.","physical":{"assetId":"DA-2026-004","stage":"PURCHASE_ORDER","location":"Not yet mobilised","quantity":4200,"unit":"Panels","productionCompletion":0,"condition":"GOOD","verificationStatus":"VERIFIED","lastVerifiedAt":"2026-08-27T11:00:00.000Z"},"financial":{"assetId":"DA-2026-004","originalValue":7800000,"currentValue":7800000,"financedAmount":0,"availableFinancing":4680000,"outstandingExposure":0,"currency":"INR","financingStatus":"UNFINANCED"},"contractual":{"assetId":"DA-2026-004","purchaseOrderNumber":"PO-ECP-2026-341","buyer":"EcoPower Projects Ltd.","supplier":"Gujarat Glass & Cell Co.","paymentTerms":"30% advance \u00b7 balance Net 45","deliveryDate":"2026-10-12","contractStatus":"Executed \u00b7 awaiting procurement","ownershipStatus":"Buyer PO committed \u00b7 title not transferred"}}}'::jsonb, '2026-08-26T09:30:00.000Z'::timestamptz, '2026-08-28T04:00:00.000Z'::timestamptz) ON CONFLICT (asset_code) DO NOTHING;
INSERT INTO verifications (asset_id, verification_type, source, status, confidence_score, evidence_reference, verified_at, metadata) SELECT a.id, 'PHYSICAL', 'VERIFICATION', 'VERIFIED', 96, 'DA-2026-004', NOW(), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-004' AND NOT EXISTS (SELECT 1 FROM verifications v WHERE v.asset_id = a.id AND v.verification_type = 'PHYSICAL' AND v.source = 'VERIFICATION');
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, new_state, metadata) SELECT a.id, 'asset', a.id::text, 'ASSET_CREATED', 'seed', jsonb_build_object('asset_code', 'DA-2026-004'), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-004' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.asset_id = a.id AND al.action = 'ASSET_CREATED' AND al.source = 'seed');

INSERT INTO assets (asset_code, asset_name, asset_type, owner_name, description, quantity, unit, current_location, lifecycle_stage, status, metadata, created_at, updated_at) VALUES ('DA-2026-005', 'Pharmaceutical Raw Materials P-563', 'Pharmaceutical Manufacturing', 'MedCore Laboratories', 'Raw materials verified and ready for production.', 12400, 'kg', 'Bengaluru Production Facility', 'RAW_MATERIAL', 'ACTIVE', '{"twin":{"id":"DA-2026-005","name":"Pharmaceutical Raw Materials P-563","category":"Pharmaceutical Manufacturing","owner":"MedCore Laboratories","buyer":"HealthFirst Pharma","supplier":"Karnataka Fine Chem","currentStage":"RAW_MATERIAL","currentValue":1840000,"originalValue":2100000,"currency":"INR","quantity":12400,"unit":"kg","location":"Bengaluru Production Facility","status":"ACTIVE","riskLevel":"MEDIUM","riskScore":38,"financingStatus":"PARTIAL","financedAmount":900000,"availableFinancing":320000,"availableAmount":320000,"createdAt":"2026-08-12T07:40:00.000Z","lastUpdated":"2026-08-27T18:20:00.000Z","situation":"Raw materials verified and ready for production.","physical":{"assetId":"DA-2026-005","stage":"RAW_MATERIAL","location":"Bengaluru Production Facility \u00b7 Cold store 2","quantity":12400,"unit":"kg","productionCompletion":0,"condition":"GOOD","verificationStatus":"VERIFIED","lastVerifiedAt":"2026-08-27T16:40:00.000Z"},"financial":{"assetId":"DA-2026-005","originalValue":2100000,"currentValue":1840000,"financedAmount":900000,"availableFinancing":320000,"outstandingExposure":900000,"currency":"INR","financingStatus":"PARTIAL"},"contractual":{"assetId":"DA-2026-005","purchaseOrderNumber":"PO-HFP-2026-563","buyer":"HealthFirst Pharma","supplier":"Karnataka Fine Chem","paymentTerms":"Net 30 Days","deliveryDate":"2026-09-09","contractStatus":"In force","ownershipStatus":"MedCore bonded inventory"}}}'::jsonb, '2026-08-12T07:40:00.000Z'::timestamptz, '2026-08-27T18:20:00.000Z'::timestamptz) ON CONFLICT (asset_code) DO NOTHING;
INSERT INTO verifications (asset_id, verification_type, source, status, confidence_score, evidence_reference, verified_at, metadata) SELECT a.id, 'PHYSICAL', 'VERIFICATION', 'VERIFIED', 91, 'DA-2026-005', NOW(), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-005' AND NOT EXISTS (SELECT 1 FROM verifications v WHERE v.asset_id = a.id AND v.verification_type = 'PHYSICAL' AND v.source = 'VERIFICATION');
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, new_state, metadata) SELECT a.id, 'asset', a.id::text, 'ASSET_CREATED', 'seed', jsonb_build_object('asset_code', 'DA-2026-005'), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-005' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.asset_id = a.id AND al.action = 'ASSET_CREATED' AND al.source = 'seed');

INSERT INTO assets (asset_code, asset_name, asset_type, owner_name, description, quantity, unit, current_location, lifecycle_stage, status, metadata, created_at, updated_at) VALUES ('DA-2026-006', 'Textile Export Batch T-912', 'Textile & Apparel', 'Heritage Textiles', 'Goods are completed and awaiting shipment.', 18000, 'Garments', 'Tiruppur finished-goods bay', 'FINISHED_GOODS', 'ACTIVE', '{"twin":{"id":"DA-2026-006","name":"Textile Export Batch T-912","category":"Textile & Apparel","owner":"Heritage Textiles","buyer":"Nordic Retail AB","supplier":"Coimbatore Spinning Cluster","currentStage":"FINISHED_GOODS","currentValue":2760000,"originalValue":2900000,"currency":"INR","quantity":18000,"unit":"Garments","location":"Tiruppur finished-goods bay","status":"ACTIVE","riskLevel":"LOW","riskScore":27,"financingStatus":"FINANCED","financedAmount":1500000,"availableFinancing":650000,"availableAmount":650000,"createdAt":"2026-07-30T04:20:00.000Z","lastUpdated":"2026-08-27T12:00:00.000Z","situation":"Goods are completed and awaiting shipment.","physical":{"assetId":"DA-2026-006","stage":"FINISHED_GOODS","location":"Tiruppur finished-goods bay","origin":"Tiruppur","destination":"Gothenburg via Chennai Port","quantity":18000,"unit":"Garments","productionCompletion":100,"condition":"GOOD","verificationStatus":"VERIFIED","lastVerifiedAt":"2026-08-27T11:30:00.000Z","shipmentStatus":"Booking confirmed \u00b7 not yet gated in"},"financial":{"assetId":"DA-2026-006","originalValue":2900000,"currentValue":2760000,"financedAmount":1500000,"availableFinancing":650000,"outstandingExposure":1500000,"currency":"INR","financingStatus":"FINANCED"},"contractual":{"assetId":"DA-2026-006","purchaseOrderNumber":"PO-NRA-2026-912","buyer":"Nordic Retail AB","supplier":"Coimbatore Spinning Cluster","paymentTerms":"LC at sight","deliveryDate":"2026-09-06","contractStatus":"In force","ownershipStatus":"Exporter until BL issuance"}}}'::jsonb, '2026-07-30T04:20:00.000Z'::timestamptz, '2026-08-27T12:00:00.000Z'::timestamptz) ON CONFLICT (asset_code) DO NOTHING;
INSERT INTO verifications (asset_id, verification_type, source, status, confidence_score, evidence_reference, verified_at, metadata) SELECT a.id, 'PHYSICAL', 'VERIFICATION', 'VERIFIED', 92, 'DA-2026-006', NOW(), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-006' AND NOT EXISTS (SELECT 1 FROM verifications v WHERE v.asset_id = a.id AND v.verification_type = 'PHYSICAL' AND v.source = 'VERIFICATION');
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, new_state, metadata) SELECT a.id, 'asset', a.id::text, 'ASSET_CREATED', 'seed', jsonb_build_object('asset_code', 'DA-2026-006'), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-006' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.asset_id = a.id AND al.action = 'ASSET_CREATED' AND al.source = 'seed');

INSERT INTO assets (asset_code, asset_name, asset_type, owner_name, description, quantity, unit, current_location, lifecycle_stage, status, metadata, created_at, updated_at) VALUES ('DA-2026-007', 'Food Processing Delivery F-110', 'Food Processing', 'FreshHarvest Foods', 'Delivery is confirmed and invoice is issued, but buyer payment is expected in 31 days.', 64, 'Pallets', 'Buyer DC · Hyderabad', 'RECEIVABLE', 'ACTIVE', '{"twin":{"id":"DA-2026-007","name":"Food Processing Delivery F-110","category":"Food Processing","owner":"FreshHarvest Foods","buyer":"National Food Distribution Ltd.","supplier":"Nashik Packhouse","currentStage":"RECEIVABLE","currentValue":2200000,"originalValue":2450000,"currency":"INR","quantity":64,"unit":"Pallets","location":"Buyer DC \u00b7 Hyderabad","status":"ACTIVE","riskLevel":"MEDIUM","riskScore":45,"financingStatus":"FINANCED","financedAmount":1600000,"availableFinancing":420000,"availableAmount":420000,"createdAt":"2026-07-18T03:00:00.000Z","lastUpdated":"2026-08-27T09:15:00.000Z","attention":true,"situation":"Delivery is confirmed and invoice is issued, but buyer payment is expected in 31 days.","physical":{"assetId":"DA-2026-007","stage":"RECEIVABLE","location":"National Food DC \u00b7 Hyderabad","quantity":64,"unit":"Pallets","productionCompletion":100,"condition":"GOOD","verificationStatus":"VERIFIED","lastVerifiedAt":"2026-08-26T14:00:00.000Z"},"financial":{"assetId":"DA-2026-007","originalValue":2450000,"currentValue":2200000,"financedAmount":1600000,"availableFinancing":420000,"outstandingExposure":1600000,"invoiceValue":2450000,"currency":"INR","financingStatus":"FINANCED"},"contractual":{"assetId":"DA-2026-007","purchaseOrderNumber":"PO-NFD-2026-110","buyer":"National Food Distribution Ltd.","supplier":"Nashik Packhouse","paymentTerms":"Net 45 Days","deliveryDate":"2026-08-26","invoiceNumber":"INV-FH-2026-4410","invoiceValue":2450000,"expectedPaymentDate":"2026-09-28","contractStatus":"Delivered \u00b7 receivable open","ownershipStatus":"Buyer accepted \u00b7 seller receivable"}}}'::jsonb, '2026-07-18T03:00:00.000Z'::timestamptz, '2026-08-27T09:15:00.000Z'::timestamptz) ON CONFLICT (asset_code) DO NOTHING;
INSERT INTO verifications (asset_id, verification_type, source, status, confidence_score, evidence_reference, verified_at, metadata) SELECT a.id, 'PHYSICAL', 'VERIFICATION', 'VERIFIED', 88, 'DA-2026-007', NOW(), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-007' AND NOT EXISTS (SELECT 1 FROM verifications v WHERE v.asset_id = a.id AND v.verification_type = 'PHYSICAL' AND v.source = 'VERIFICATION');
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, new_state, metadata) SELECT a.id, 'asset', a.id::text, 'ASSET_CREATED', 'seed', jsonb_build_object('asset_code', 'DA-2026-007'), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-007' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.asset_id = a.id AND al.action = 'ASSET_CREATED' AND al.source = 'seed');

INSERT INTO assets (asset_code, asset_name, asset_type, owner_name, description, quantity, unit, current_location, lifecycle_stage, status, metadata, created_at, updated_at) VALUES ('DA-2026-008', 'Medical Equipment Order H-680', 'Healthcare Equipment', 'CareTech Manufacturing', 'Buyer payment was received and the financing lifecycle was successfully settled.', 12, 'Systems', 'MedLife Hospitals · settled', 'CASH_REALISED', 'SETTLED', '{"twin":{"id":"DA-2026-008","name":"Medical Equipment Order H-680","category":"Healthcare Equipment","owner":"CareTech Manufacturing","buyer":"MedLife Hospitals","supplier":"CareTech Tooling Unit","currentStage":"CASH_REALISED","currentValue":0,"originalValue":3600000,"currency":"INR","quantity":12,"unit":"Systems","location":"MedLife Hospitals \u00b7 settled","status":"SETTLED","riskLevel":"CLOSED","riskScore":0,"financingStatus":"SETTLED","financedAmount":0,"availableFinancing":0,"availableAmount":0,"createdAt":"2026-05-04T08:00:00.000Z","lastUpdated":"2026-08-21T11:00:00.000Z","situation":"Buyer payment was received and the financing lifecycle was successfully settled.","physical":{"assetId":"DA-2026-008","stage":"CASH_REALISED","location":"Installed at MedLife Hospitals","quantity":12,"unit":"Systems","productionCompletion":100,"condition":"SETTLED","verificationStatus":"VERIFIED","lastVerifiedAt":"2026-08-21T10:40:00.000Z"},"financial":{"assetId":"DA-2026-008","originalValue":3600000,"currentValue":0,"financedAmount":0,"availableFinancing":0,"outstandingExposure":0,"invoiceValue":3600000,"currency":"INR","financingStatus":"SETTLED"},"contractual":{"assetId":"DA-2026-008","purchaseOrderNumber":"PO-MLH-2026-680","buyer":"MedLife Hospitals","supplier":"CareTech Tooling Unit","paymentTerms":"Net 30 Days","deliveryDate":"2026-07-28","invoiceNumber":"INV-CT-2026-680","invoiceValue":3600000,"expectedPaymentDate":"2026-08-20","contractStatus":"Closed","ownershipStatus":"Transferred \u00b7 cash realised"}}}'::jsonb, '2026-05-04T08:00:00.000Z'::timestamptz, '2026-08-21T11:00:00.000Z'::timestamptz) ON CONFLICT (asset_code) DO NOTHING;
INSERT INTO verifications (asset_id, verification_type, source, status, confidence_score, evidence_reference, verified_at, metadata) SELECT a.id, 'PHYSICAL', 'VERIFICATION', 'VERIFIED', 99, 'DA-2026-008', NOW(), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-008' AND NOT EXISTS (SELECT 1 FROM verifications v WHERE v.asset_id = a.id AND v.verification_type = 'PHYSICAL' AND v.source = 'VERIFICATION');
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, new_state, metadata) SELECT a.id, 'asset', a.id::text, 'ASSET_CREATED', 'seed', jsonb_build_object('asset_code', 'DA-2026-008'), '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-008' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.asset_id = a.id AND al.action = 'ASSET_CREATED' AND al.source = 'seed');

INSERT INTO asset_events (event_code, asset_id, event_type, source, event_timestamp, payload, severity, status, idempotency_key, processed, processed_at) SELECT 'SEED-001-PROGRESS-65', a.id, 'PRODUCTION_PROGRESS_UPDATED', 'PRODUCTION', '2026-08-28T07:20:00.000Z'::timestamptz, '{"completionPercentage":65,"value":4250000}'::jsonb, 'info', 'APPLIED', 'SEED-001-PROGRESS-65', TRUE, NOW() FROM assets a WHERE a.asset_code = 'DA-2026-001' ON CONFLICT (idempotency_key) DO NOTHING;
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, metadata) SELECT a.id, 'event', 'SEED-001-PROGRESS-65', 'EVENT_PROCESSED', 'seed', '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-001' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.entity_id = 'SEED-001-PROGRESS-65' AND al.action = 'EVENT_PROCESSED');

INSERT INTO asset_events (event_code, asset_id, event_type, source, event_timestamp, payload, severity, status, idempotency_key, processed, processed_at) SELECT 'SEED-002-SHIPMENT', a.id, 'SHIPMENT_CREATED', 'LOGISTICS', '2026-08-27T03:30:00.000Z'::timestamptz, '{"shipmentId":"SHP-C219"}'::jsonb, 'info', 'APPLIED', 'SEED-002-SHIPMENT', TRUE, NOW() FROM assets a WHERE a.asset_code = 'DA-2026-002' ON CONFLICT (idempotency_key) DO NOTHING;
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, metadata) SELECT a.id, 'event', 'SEED-002-SHIPMENT', 'EVENT_PROCESSED', 'seed', '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-002' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.entity_id = 'SEED-002-SHIPMENT' AND al.action = 'EVENT_PROCESSED');

INSERT INTO asset_events (event_code, asset_id, event_type, source, event_timestamp, payload, severity, status, idempotency_key, processed, processed_at) SELECT 'SEED-003-MISMATCH', a.id, 'QUANTITY_MISMATCH_DETECTED', 'WAREHOUSE', '2026-08-28T05:02:00.000Z'::timestamptz, '{"expectedQuantity":1200,"actualQuantity":1140}'::jsonb, 'warning', 'APPLIED', 'SEED-003-MISMATCH', TRUE, NOW() FROM assets a WHERE a.asset_code = 'DA-2026-003' ON CONFLICT (idempotency_key) DO NOTHING;
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, metadata) SELECT a.id, 'event', 'SEED-003-MISMATCH', 'EVENT_PROCESSED', 'seed', '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-003' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.entity_id = 'SEED-003-MISMATCH' AND al.action = 'EVENT_PROCESSED');

INSERT INTO asset_events (event_code, asset_id, event_type, source, event_timestamp, payload, severity, status, idempotency_key, processed, processed_at) SELECT 'SEED-004-PO', a.id, 'PURCHASE_ORDER_VERIFIED', 'ERP', '2026-08-27T11:00:00.000Z'::timestamptz, '{"po":"PO-ECP-2026-341"}'::jsonb, 'success', 'APPLIED', 'SEED-004-PO', TRUE, NOW() FROM assets a WHERE a.asset_code = 'DA-2026-004' ON CONFLICT (idempotency_key) DO NOTHING;
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, metadata) SELECT a.id, 'event', 'SEED-004-PO', 'EVENT_PROCESSED', 'seed', '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-004' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.entity_id = 'SEED-004-PO' AND al.action = 'EVENT_PROCESSED');

INSERT INTO asset_events (event_code, asset_id, event_type, source, event_timestamp, payload, severity, status, idempotency_key, processed, processed_at) SELECT 'SEED-005-PROCURE', a.id, 'PROCUREMENT_COMPLETED', 'ERP', '2026-08-27T16:40:00.000Z'::timestamptz, '{}'::jsonb, 'info', 'APPLIED', 'SEED-005-PROCURE', TRUE, NOW() FROM assets a WHERE a.asset_code = 'DA-2026-005' ON CONFLICT (idempotency_key) DO NOTHING;
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, metadata) SELECT a.id, 'event', 'SEED-005-PROCURE', 'EVENT_PROCESSED', 'seed', '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-005' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.entity_id = 'SEED-005-PROCURE' AND al.action = 'EVENT_PROCESSED');

INSERT INTO asset_events (event_code, asset_id, event_type, source, event_timestamp, payload, severity, status, idempotency_key, processed, processed_at) SELECT 'SEED-006-FG', a.id, 'FINISHED_GOODS_CONFIRMED', 'PRODUCTION', '2026-08-27T11:30:00.000Z'::timestamptz, '{}'::jsonb, 'success', 'APPLIED', 'SEED-006-FG', TRUE, NOW() FROM assets a WHERE a.asset_code = 'DA-2026-006' ON CONFLICT (idempotency_key) DO NOTHING;
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, metadata) SELECT a.id, 'event', 'SEED-006-FG', 'EVENT_PROCESSED', 'seed', '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-006' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.entity_id = 'SEED-006-FG' AND al.action = 'EVENT_PROCESSED');

INSERT INTO asset_events (event_code, asset_id, event_type, source, event_timestamp, payload, severity, status, idempotency_key, processed, processed_at) SELECT 'SEED-007-PAY', a.id, 'PAYMENT_DELAY_DETECTED', 'FINANCE', '2026-08-28T08:00:00.000Z'::timestamptz, '{"invoice":"INV-FH-2026-4410"}'::jsonb, 'warning', 'APPLIED', 'SEED-007-PAY', TRUE, NOW() FROM assets a WHERE a.asset_code = 'DA-2026-007' ON CONFLICT (idempotency_key) DO NOTHING;
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, metadata) SELECT a.id, 'event', 'SEED-007-PAY', 'EVENT_PROCESSED', 'seed', '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-007' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.entity_id = 'SEED-007-PAY' AND al.action = 'EVENT_PROCESSED');

INSERT INTO asset_events (event_code, asset_id, event_type, source, event_timestamp, payload, severity, status, idempotency_key, processed, processed_at) SELECT 'SEED-008-CASH', a.id, 'PAYMENT_RECEIVED', 'FINANCE', '2026-08-21T10:40:00.000Z'::timestamptz, '{"amount":3600000}'::jsonb, 'success', 'APPLIED', 'SEED-008-CASH', TRUE, NOW() FROM assets a WHERE a.asset_code = 'DA-2026-008' ON CONFLICT (idempotency_key) DO NOTHING;
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, metadata) SELECT a.id, 'event', 'SEED-008-CASH', 'EVENT_PROCESSED', 'seed', '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-008' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.entity_id = 'SEED-008-CASH' AND al.action = 'EVENT_PROCESSED');

INSERT INTO conflicts (conflict_code, asset_id, conflict_type, severity, status, description, expected_value, actual_value, difference_value) SELECT 'CFL-DA-2026-003-QUANTITY_MISMATCH', a.id, 'QUANTITY_MISMATCH', 'HIGH', 'OPEN', '60-unit discrepancy between production (1,200) and warehouse (1,140) records.', '1200', '1140', '60' FROM assets a WHERE a.asset_code = 'DA-2026-003' ON CONFLICT (conflict_code) DO NOTHING;
INSERT INTO audit_logs (asset_id, entity_type, entity_id, action, source, metadata) SELECT a.id, 'conflict', 'CFL-DA-2026-003-QUANTITY_MISMATCH', 'CONFLICT_DETECTED', 'seed', '{"seed": true}'::jsonb FROM assets a WHERE a.asset_code = 'DA-2026-003' AND NOT EXISTS (SELECT 1 FROM audit_logs al WHERE al.entity_id = 'CFL-DA-2026-003-QUANTITY_MISMATCH' AND al.action = 'CONFLICT_DETECTED');
