DEMO_ASSETS = [
    {
        "asset_code": "DA-2026-001",
        "asset_name": "Automotive Components Batch A-452",
        "asset_type": "Automotive Manufacturing",
        "owner_name": "Nova Manufacturing Pvt. Ltd.",
        "description": "Production is progressing but there is a 2-day production delay caused by a delayed raw-material delivery.",
        "quantity": 18500,
        "unit": "Units",
        "current_location": "Chennai Manufacturing Facility",
        "lifecycle_stage": "PRODUCTION",
        "status": "ACTIVE",
        "verification_status": "VERIFIED",
        "confidence_score": 94,
        "created_at": "2026-08-15T06:10:00.000Z",
        "updated_at": "2026-08-28T07:27:00.000Z",
        "metadata": {
            "twin": {
                "id": "DA-2026-001",
                "name": "Automotive Components Batch A-452",
                "category": "Automotive Manufacturing",
                "owner": "Nova Manufacturing Pvt. Ltd.",
                "buyer": "Apex Mobility Ltd.",
                "supplier": "Precision Metals India",
                "currentStage": "PRODUCTION",
                "currentValue": 4250000,
                "originalValue": 5500000,
                "currency": "INR",
                "quantity": 18500,
                "unit": "Units",
                "location": "Chennai Manufacturing Facility",
                "status": "ACTIVE",
                "riskLevel": "MEDIUM",
                "riskScore": 42,
                "financingStatus": "PARTIAL",
                "financedAmount": 2500000,
                "availableFinancing": 730000,
                "availableAmount": 730000,
                "createdAt": "2026-08-15T06:10:00.000Z",
                "lastUpdated": "2026-08-28T07:27:00.000Z",
                "attention": True,
                "situation": "Production is progressing but there is a 2-day production delay caused by a delayed raw-material delivery.",
                "physical": {
                    "assetId": "DA-2026-001",
                    "stage": "PRODUCTION",
                    "location": "Chennai Manufacturing Facility",
                    "quantity": 18500,
                    "unit": "Units",
                    "productionCompletion": 65,
                    "condition": "GOOD",
                    "verificationStatus": "VERIFIED",
                    "lastVerifiedAt": "2026-08-28T07:20:00.000Z",
                },
                "financial": {
                    "assetId": "DA-2026-001",
                    "originalValue": 5500000,
                    "currentValue": 4250000,
                    "financedAmount": 2500000,
                    "availableFinancing": 730000,
                    "outstandingExposure": 2500000,
                    "currency": "INR",
                    "financingStatus": "PARTIAL",
                },
                "contractual": {
                    "assetId": "DA-2026-001",
                    "purchaseOrderNumber": "PO-APX-2026-0842",
                    "buyer": "Apex Mobility Ltd.",
                    "supplier": "Precision Metals India",
                    "paymentTerms": "Net 60 Days",
                    "deliveryDate": "2026-09-18",
                    "contractStatus": "In force",
                    "ownershipStatus": "Supplier / work-in-progress",
                },
            }
        },
    },
    {
        "asset_code": "DA-2026-002",
        "asset_name": "Consumer Electronics Shipment C-219",
        "asset_type": "Consumer Electronics",
        "owner_name": "Vertex Electronics Ltd.",
        "description": "Shipment is on schedule. Eligible for transition from finished-goods to in-transit financing.",
        "quantity": 2400,
        "unit": "Cartons",
        "current_location": "Chennai → Mumbai",
        "lifecycle_stage": "IN_TRANSIT",
        "status": "ACTIVE",
        "verification_status": "VERIFIED",
        "confidence_score": 93,
        "created_at": "2026-08-08T05:00:00.000Z",
        "updated_at": "2026-08-28T06:40:00.000Z",
        "metadata": {
            "twin": {
                "id": "DA-2026-002",
                "name": "Consumer Electronics Shipment C-219",
                "category": "Consumer Electronics",
                "owner": "Vertex Electronics Ltd.",
                "buyer": "Metro Retail India",
                "supplier": "Helio Components Shenzhen",
                "currentStage": "IN_TRANSIT",
                "currentValue": 3180000,
                "originalValue": 3400000,
                "currency": "INR",
                "quantity": 2400,
                "unit": "Cartons",
                "location": "Chennai → Mumbai",
                "status": "ACTIVE",
                "riskLevel": "LOW",
                "riskScore": 24,
                "financingStatus": "FINANCED",
                "financedAmount": 1800000,
                "availableFinancing": 540000,
                "availableAmount": 540000,
                "createdAt": "2026-08-08T05:00:00.000Z",
                "lastUpdated": "2026-08-28T06:40:00.000Z",
                "situation": "Shipment is on schedule. Eligible for transition from finished-goods to in-transit financing.",
                "physical": {
                    "assetId": "DA-2026-002",
                    "stage": "IN_TRANSIT",
                    "location": "NH-48 corridor, near Pune",
                    "origin": "Chennai CFS",
                    "destination": "Mumbai Bhiwandi DC",
                    "quantity": 2400,
                    "unit": "Cartons",
                    "productionCompletion": 100,
                    "condition": "GOOD",
                    "verificationStatus": "VERIFIED",
                    "lastVerifiedAt": "2026-08-28T04:15:00.000Z",
                    "shipmentStatus": "On schedule · ETA 30 Aug",
                },
                "financial": {
                    "assetId": "DA-2026-002",
                    "originalValue": 3400000,
                    "currentValue": 3180000,
                    "financedAmount": 1800000,
                    "availableFinancing": 540000,
                    "outstandingExposure": 1800000,
                    "currency": "INR",
                    "financingStatus": "FINANCED",
                },
                "contractual": {
                    "assetId": "DA-2026-002",
                    "purchaseOrderNumber": "PO-MRI-2026-219",
                    "buyer": "Metro Retail India",
                    "supplier": "Helio Components Shenzhen",
                    "paymentTerms": "Net 45 Days",
                    "deliveryDate": "2026-08-30",
                    "contractStatus": "In force",
                    "ownershipStatus": "In transit · seller until DC scan",
                },
            }
        },
    },
    {
        "asset_code": "DA-2026-003",
        "asset_name": "Industrial Machinery Components M-778",
        "asset_type": "Industrial Equipment",
        "owner_name": "Titan Industrial Systems",
        "description": "A quantity mismatch was detected between production records and warehouse records.",
        "quantity": 86,
        "unit": "Assemblies",
        "current_location": "Pune Central Warehouse",
        "lifecycle_stage": "WAREHOUSE",
        "status": "WATCH",
        "verification_status": "FAILED",
        "confidence_score": 58,
        "created_at": "2026-07-22T08:00:00.000Z",
        "updated_at": "2026-08-28T05:10:00.000Z",
        "metadata": {
            "twin": {
                "id": "DA-2026-003",
                "name": "Industrial Machinery Components M-778",
                "category": "Industrial Equipment",
                "owner": "Titan Industrial Systems",
                "buyer": "Global Engineering Corp.",
                "supplier": "ForgeWorks Pune",
                "currentStage": "WAREHOUSE",
                "currentValue": 5620000,
                "originalValue": 5900000,
                "currency": "INR",
                "quantity": 86,
                "unit": "Assemblies",
                "location": "Pune Central Warehouse",
                "status": "WATCH",
                "riskLevel": "HIGH",
                "riskScore": 76,
                "financingStatus": "PENDING_REVIEW",
                "financedAmount": 3900000,
                "availableFinancing": 210000,
                "availableAmount": 210000,
                "createdAt": "2026-07-22T08:00:00.000Z",
                "lastUpdated": "2026-08-28T05:10:00.000Z",
                "attention": True,
                "situation": "A quantity mismatch was detected between production records and warehouse records.",
                "physical": {
                    "assetId": "DA-2026-003",
                    "stage": "WAREHOUSE",
                    "location": "Pune Central Warehouse · Bay 12",
                    "quantity": 86,
                    "unit": "Assemblies",
                    "productionCompletion": 100,
                    "condition": "WATCH",
                    "verificationStatus": "MISMATCH",
                    "lastVerifiedAt": "2026-08-28T05:02:00.000Z",
                },
                "financial": {
                    "assetId": "DA-2026-003",
                    "originalValue": 5900000,
                    "currentValue": 5620000,
                    "financedAmount": 3900000,
                    "availableFinancing": 210000,
                    "outstandingExposure": 3900000,
                    "currency": "INR",
                    "financingStatus": "PENDING_REVIEW",
                },
                "contractual": {
                    "assetId": "DA-2026-003",
                    "purchaseOrderNumber": "PO-GEC-2026-778",
                    "buyer": "Global Engineering Corp.",
                    "supplier": "ForgeWorks Pune",
                    "paymentTerms": "Net 30 Days after GRN",
                    "deliveryDate": "2026-09-04",
                    "contractStatus": "Held pending reconciliation",
                    "ownershipStatus": "Warehouse receipt · disputed quantity",
                },
            }
        },
    },
    {
        "asset_code": "DA-2026-004",
        "asset_name": "Solar Panel Manufacturing Order S-341",
        "asset_type": "Renewable Energy",
        "owner_name": "SunGrid Technologies",
        "description": "Verified purchase order received and procurement financing opportunity identified.",
        "quantity": 4200,
        "unit": "Panels",
        "current_location": "PO desk · Ahmedabad",
        "lifecycle_stage": "PURCHASE_ORDER",
        "status": "ACTIVE",
        "verification_status": "VERIFIED",
        "confidence_score": 96,
        "created_at": "2026-08-26T09:30:00.000Z",
        "updated_at": "2026-08-28T04:00:00.000Z",
        "metadata": {"twin": {"id": "DA-2026-004", "name": "Solar Panel Manufacturing Order S-341", "category": "Renewable Energy", "owner": "SunGrid Technologies", "buyer": "EcoPower Projects Ltd.", "supplier": "Gujarat Glass & Cell Co.", "currentStage": "PURCHASE_ORDER", "currentValue": 7800000, "originalValue": 7800000, "currency": "INR", "quantity": 4200, "unit": "Panels", "location": "PO desk · Ahmedabad", "status": "ACTIVE", "riskLevel": "LOW", "riskScore": 18, "financingStatus": "UNFINANCED", "financedAmount": 0, "availableFinancing": 4680000, "availableAmount": 4680000, "createdAt": "2026-08-26T09:30:00.000Z", "lastUpdated": "2026-08-28T04:00:00.000Z", "situation": "Verified purchase order received and procurement financing opportunity identified.", "physical": {"assetId": "DA-2026-004", "stage": "PURCHASE_ORDER", "location": "Not yet mobilised", "quantity": 4200, "unit": "Panels", "productionCompletion": 0, "condition": "GOOD", "verificationStatus": "VERIFIED", "lastVerifiedAt": "2026-08-27T11:00:00.000Z"}, "financial": {"assetId": "DA-2026-004", "originalValue": 7800000, "currentValue": 7800000, "financedAmount": 0, "availableFinancing": 4680000, "outstandingExposure": 0, "currency": "INR", "financingStatus": "UNFINANCED"}, "contractual": {"assetId": "DA-2026-004", "purchaseOrderNumber": "PO-ECP-2026-341", "buyer": "EcoPower Projects Ltd.", "supplier": "Gujarat Glass & Cell Co.", "paymentTerms": "30% advance · balance Net 45", "deliveryDate": "2026-10-12", "contractStatus": "Executed · awaiting procurement", "ownershipStatus": "Buyer PO committed · title not transferred"}}},
    },
    {
        "asset_code": "DA-2026-005",
        "asset_name": "Pharmaceutical Raw Materials P-563",
        "asset_type": "Pharmaceutical Manufacturing",
        "owner_name": "MedCore Laboratories",
        "description": "Raw materials verified and ready for production.",
        "quantity": 12400,
        "unit": "kg",
        "current_location": "Bengaluru Production Facility",
        "lifecycle_stage": "RAW_MATERIAL",
        "status": "ACTIVE",
        "verification_status": "VERIFIED",
        "confidence_score": 91,
        "created_at": "2026-08-12T07:40:00.000Z",
        "updated_at": "2026-08-27T18:20:00.000Z",
        "metadata": {"twin": {"id": "DA-2026-005", "name": "Pharmaceutical Raw Materials P-563", "category": "Pharmaceutical Manufacturing", "owner": "MedCore Laboratories", "buyer": "HealthFirst Pharma", "supplier": "Karnataka Fine Chem", "currentStage": "RAW_MATERIAL", "currentValue": 1840000, "originalValue": 2100000, "currency": "INR", "quantity": 12400, "unit": "kg", "location": "Bengaluru Production Facility", "status": "ACTIVE", "riskLevel": "MEDIUM", "riskScore": 38, "financingStatus": "PARTIAL", "financedAmount": 900000, "availableFinancing": 320000, "availableAmount": 320000, "createdAt": "2026-08-12T07:40:00.000Z", "lastUpdated": "2026-08-27T18:20:00.000Z", "situation": "Raw materials verified and ready for production.", "physical": {"assetId": "DA-2026-005", "stage": "RAW_MATERIAL", "location": "Bengaluru Production Facility · Cold store 2", "quantity": 12400, "unit": "kg", "productionCompletion": 0, "condition": "GOOD", "verificationStatus": "VERIFIED", "lastVerifiedAt": "2026-08-27T16:40:00.000Z"}, "financial": {"assetId": "DA-2026-005", "originalValue": 2100000, "currentValue": 1840000, "financedAmount": 900000, "availableFinancing": 320000, "outstandingExposure": 900000, "currency": "INR", "financingStatus": "PARTIAL"}, "contractual": {"assetId": "DA-2026-005", "purchaseOrderNumber": "PO-HFP-2026-563", "buyer": "HealthFirst Pharma", "supplier": "Karnataka Fine Chem", "paymentTerms": "Net 30 Days", "deliveryDate": "2026-09-09", "contractStatus": "In force", "ownershipStatus": "MedCore bonded inventory"}}},
    },
    {
        "asset_code": "DA-2026-006",
        "asset_name": "Textile Export Batch T-912",
        "asset_type": "Textile & Apparel",
        "owner_name": "Heritage Textiles",
        "description": "Goods are completed and awaiting shipment.",
        "quantity": 18000,
        "unit": "Garments",
        "current_location": "Tiruppur finished-goods bay",
        "lifecycle_stage": "FINISHED_GOODS",
        "status": "ACTIVE",
        "verification_status": "VERIFIED",
        "confidence_score": 92,
        "created_at": "2026-07-30T04:20:00.000Z",
        "updated_at": "2026-08-27T12:00:00.000Z",
        "metadata": {"twin": {"id": "DA-2026-006", "name": "Textile Export Batch T-912", "category": "Textile & Apparel", "owner": "Heritage Textiles", "buyer": "Nordic Retail AB", "supplier": "Coimbatore Spinning Cluster", "currentStage": "FINISHED_GOODS", "currentValue": 2760000, "originalValue": 2900000, "currency": "INR", "quantity": 18000, "unit": "Garments", "location": "Tiruppur finished-goods bay", "status": "ACTIVE", "riskLevel": "LOW", "riskScore": 27, "financingStatus": "FINANCED", "financedAmount": 1500000, "availableFinancing": 650000, "availableAmount": 650000, "createdAt": "2026-07-30T04:20:00.000Z", "lastUpdated": "2026-08-27T12:00:00.000Z", "situation": "Goods are completed and awaiting shipment.", "physical": {"assetId": "DA-2026-006", "stage": "FINISHED_GOODS", "location": "Tiruppur finished-goods bay", "origin": "Tiruppur", "destination": "Gothenburg via Chennai Port", "quantity": 18000, "unit": "Garments", "productionCompletion": 100, "condition": "GOOD", "verificationStatus": "VERIFIED", "lastVerifiedAt": "2026-08-27T11:30:00.000Z", "shipmentStatus": "Booking confirmed · not yet gated in"}, "financial": {"assetId": "DA-2026-006", "originalValue": 2900000, "currentValue": 2760000, "financedAmount": 1500000, "availableFinancing": 650000, "outstandingExposure": 1500000, "currency": "INR", "financingStatus": "FINANCED"}, "contractual": {"assetId": "DA-2026-006", "purchaseOrderNumber": "PO-NRA-2026-912", "buyer": "Nordic Retail AB", "supplier": "Coimbatore Spinning Cluster", "paymentTerms": "LC at sight", "deliveryDate": "2026-09-06", "contractStatus": "In force", "ownershipStatus": "Exporter until BL issuance"}}},
    },
    {
        "asset_code": "DA-2026-007",
        "asset_name": "Food Processing Delivery F-110",
        "asset_type": "Food Processing",
        "owner_name": "FreshHarvest Foods",
        "description": "Delivery is confirmed and invoice is issued, but buyer payment is expected in 31 days.",
        "quantity": 64,
        "unit": "Pallets",
        "current_location": "Buyer DC · Hyderabad",
        "lifecycle_stage": "RECEIVABLE",
        "status": "ACTIVE",
        "verification_status": "VERIFIED",
        "confidence_score": 88,
        "created_at": "2026-07-18T03:00:00.000Z",
        "updated_at": "2026-08-27T09:15:00.000Z",
        "metadata": {"twin": {"id": "DA-2026-007", "name": "Food Processing Delivery F-110", "category": "Food Processing", "owner": "FreshHarvest Foods", "buyer": "National Food Distribution Ltd.", "supplier": "Nashik Packhouse", "currentStage": "RECEIVABLE", "currentValue": 2200000, "originalValue": 2450000, "currency": "INR", "quantity": 64, "unit": "Pallets", "location": "Buyer DC · Hyderabad", "status": "ACTIVE", "riskLevel": "MEDIUM", "riskScore": 45, "financingStatus": "FINANCED", "financedAmount": 1600000, "availableFinancing": 420000, "availableAmount": 420000, "createdAt": "2026-07-18T03:00:00.000Z", "lastUpdated": "2026-08-27T09:15:00.000Z", "attention": True, "situation": "Delivery is confirmed and invoice is issued, but buyer payment is expected in 31 days.", "physical": {"assetId": "DA-2026-007", "stage": "RECEIVABLE", "location": "National Food DC · Hyderabad", "quantity": 64, "unit": "Pallets", "productionCompletion": 100, "condition": "GOOD", "verificationStatus": "VERIFIED", "lastVerifiedAt": "2026-08-26T14:00:00.000Z"}, "financial": {"assetId": "DA-2026-007", "originalValue": 2450000, "currentValue": 2200000, "financedAmount": 1600000, "availableFinancing": 420000, "outstandingExposure": 1600000, "invoiceValue": 2450000, "currency": "INR", "financingStatus": "FINANCED"}, "contractual": {"assetId": "DA-2026-007", "purchaseOrderNumber": "PO-NFD-2026-110", "buyer": "National Food Distribution Ltd.", "supplier": "Nashik Packhouse", "paymentTerms": "Net 45 Days", "deliveryDate": "2026-08-26", "invoiceNumber": "INV-FH-2026-4410", "invoiceValue": 2450000, "expectedPaymentDate": "2026-09-28", "contractStatus": "Delivered · receivable open", "ownershipStatus": "Buyer accepted · seller receivable"}}},
    },
    {
        "asset_code": "DA-2026-008",
        "asset_name": "Medical Equipment Order H-680",
        "asset_type": "Healthcare Equipment",
        "owner_name": "CareTech Manufacturing",
        "description": "Buyer payment was received and the financing lifecycle was successfully settled.",
        "quantity": 12,
        "unit": "Systems",
        "current_location": "MedLife Hospitals · settled",
        "lifecycle_stage": "CASH_REALISED",
        "status": "SETTLED",
        "verification_status": "VERIFIED",
        "confidence_score": 99,
        "created_at": "2026-05-04T08:00:00.000Z",
        "updated_at": "2026-08-21T11:00:00.000Z",
        "metadata": {"twin": {"id": "DA-2026-008", "name": "Medical Equipment Order H-680", "category": "Healthcare Equipment", "owner": "CareTech Manufacturing", "buyer": "MedLife Hospitals", "supplier": "CareTech Tooling Unit", "currentStage": "CASH_REALISED", "currentValue": 0, "originalValue": 3600000, "currency": "INR", "quantity": 12, "unit": "Systems", "location": "MedLife Hospitals · settled", "status": "SETTLED", "riskLevel": "CLOSED", "riskScore": 0, "financingStatus": "SETTLED", "financedAmount": 0, "availableFinancing": 0, "availableAmount": 0, "createdAt": "2026-05-04T08:00:00.000Z", "lastUpdated": "2026-08-21T11:00:00.000Z", "situation": "Buyer payment was received and the financing lifecycle was successfully settled.", "physical": {"assetId": "DA-2026-008", "stage": "CASH_REALISED", "location": "Installed at MedLife Hospitals", "quantity": 12, "unit": "Systems", "productionCompletion": 100, "condition": "SETTLED", "verificationStatus": "VERIFIED", "lastVerifiedAt": "2026-08-21T10:40:00.000Z"}, "financial": {"assetId": "DA-2026-008", "originalValue": 3600000, "currentValue": 0, "financedAmount": 0, "availableFinancing": 0, "outstandingExposure": 0, "invoiceValue": 3600000, "currency": "INR", "financingStatus": "SETTLED"}, "contractual": {"assetId": "DA-2026-008", "purchaseOrderNumber": "PO-MLH-2026-680", "buyer": "MedLife Hospitals", "supplier": "CareTech Tooling Unit", "paymentTerms": "Net 30 Days", "deliveryDate": "2026-07-28", "invoiceNumber": "INV-CT-2026-680", "invoiceValue": 3600000, "expectedPaymentDate": "2026-08-20", "contractStatus": "Closed", "ownershipStatus": "Transferred · cash realised"}}},
    },
]

FOUNDATIONAL_EVENTS = [
    {"event_code": "SEED-001-PROGRESS-65", "idempotency_key": "SEED-001-PROGRESS-65", "asset_code": "DA-2026-001", "event_type": "PRODUCTION_PROGRESS_UPDATED", "source": "PRODUCTION", "event_timestamp": "2026-08-28T07:20:00.000Z", "severity": "info", "payload": {"completionPercentage": 65, "value": 4250000}},
    {"event_code": "SEED-002-SHIPMENT", "idempotency_key": "SEED-002-SHIPMENT", "asset_code": "DA-2026-002", "event_type": "SHIPMENT_CREATED", "source": "LOGISTICS", "event_timestamp": "2026-08-27T03:30:00.000Z", "severity": "info", "payload": {"shipmentId": "SHP-C219"}},
    {"event_code": "SEED-003-MISMATCH", "idempotency_key": "SEED-003-MISMATCH", "asset_code": "DA-2026-003", "event_type": "QUANTITY_MISMATCH_DETECTED", "source": "WAREHOUSE", "event_timestamp": "2026-08-28T05:02:00.000Z", "severity": "warning", "payload": {"expectedQuantity": 1200, "actualQuantity": 1140}},
    {"event_code": "SEED-004-PO", "idempotency_key": "SEED-004-PO", "asset_code": "DA-2026-004", "event_type": "PURCHASE_ORDER_VERIFIED", "source": "ERP", "event_timestamp": "2026-08-27T11:00:00.000Z", "severity": "success", "payload": {"po": "PO-ECP-2026-341"}},
    {"event_code": "SEED-005-PROCURE", "idempotency_key": "SEED-005-PROCURE", "asset_code": "DA-2026-005", "event_type": "PROCUREMENT_COMPLETED", "source": "ERP", "event_timestamp": "2026-08-27T16:40:00.000Z", "severity": "info", "payload": {}},
    {"event_code": "SEED-006-FG", "idempotency_key": "SEED-006-FG", "asset_code": "DA-2026-006", "event_type": "FINISHED_GOODS_CONFIRMED", "source": "PRODUCTION", "event_timestamp": "2026-08-27T11:30:00.000Z", "severity": "success", "payload": {}},
    {"event_code": "SEED-007-PAY", "idempotency_key": "SEED-007-PAY", "asset_code": "DA-2026-007", "event_type": "PAYMENT_DELAY_DETECTED", "source": "FINANCE", "event_timestamp": "2026-08-28T08:00:00.000Z", "severity": "warning", "payload": {"invoice": "INV-FH-2026-4410"}},
    {"event_code": "SEED-008-CASH", "idempotency_key": "SEED-008-CASH", "asset_code": "DA-2026-008", "event_type": "PAYMENT_RECEIVED", "source": "FINANCE", "event_timestamp": "2026-08-21T10:40:00.000Z", "severity": "success", "payload": {"amount": 3600000}},
]

SEED_CONFLICTS = [
    {
        "conflict_code": "CFL-DA-2026-003-QUANTITY_MISMATCH",
        "asset_code": "DA-2026-003",
        "conflict_type": "QUANTITY_MISMATCH",
        "severity": "HIGH",
        "description": "60-unit discrepancy between production (1,200) and warehouse (1,140) records.",
        "expected_value": "1200",
        "actual_value": "1140",
        "difference_value": "60",
    }
]
