import type { Asset } from "@/types/asset";
import { companies } from "@/lib/demo-data/companies";

function twin(asset: Omit<Asset, "physical" | "financial" | "contractual" | "availableAmount"> & {
  physical: Asset["physical"];
  financial: Asset["financial"];
  contractual: Asset["contractual"];
}): Asset {
  return {
    ...asset,
    availableAmount: asset.availableFinancing,
  };
}

export const PRIMARY_ASSET_ID = "DA-2026-001";

export const baseAssets: Asset[] = [
  twin({
    id: PRIMARY_ASSET_ID,
    name: "Automotive Components Batch A-452",
    category: "Automotive Manufacturing",
    owner: companies.nova,
    buyer: companies.apex,
    supplier: companies.precision,
    currentStage: "PRODUCTION",
    currentValue: 4_250_000,
    originalValue: 5_500_000,
    currency: "INR",
    quantity: 18_500,
    unit: "Units",
    location: "Chennai Manufacturing Facility",
    status: "ACTIVE",
    riskLevel: "MEDIUM",
    riskScore: 42,
    financingStatus: "PARTIAL",
    financedAmount: 2_500_000,
    availableFinancing: 730_000,
    createdAt: "2026-08-15T06:10:00.000Z",
    lastUpdated: "2026-08-28T07:27:00.000Z",
    attention: true,
    situation:
      "Production is progressing but there is a 2-day production delay caused by a delayed raw-material delivery.",
    physical: {
      assetId: PRIMARY_ASSET_ID,
      stage: "PRODUCTION",
      location: "Chennai Manufacturing Facility",
      quantity: 18_500,
      unit: "Units",
      productionCompletion: 65,
      condition: "GOOD",
      verificationStatus: "VERIFIED",
      lastVerifiedAt: "2026-08-28T07:20:00.000Z",
    },
    financial: {
      assetId: PRIMARY_ASSET_ID,
      originalValue: 5_500_000,
      currentValue: 4_250_000,
      financedAmount: 2_500_000,
      availableFinancing: 730_000,
      outstandingExposure: 2_500_000,
      currency: "INR",
      financingStatus: "PARTIAL",
    },
    contractual: {
      assetId: PRIMARY_ASSET_ID,
      purchaseOrderNumber: "PO-APX-2026-0842",
      buyer: companies.apex,
      supplier: companies.precision,
      paymentTerms: "Net 60 Days",
      deliveryDate: "2026-09-18",
      contractStatus: "In force",
      ownershipStatus: "Supplier / work-in-progress",
    },
  }),
  twin({
    id: "DA-2026-002",
    name: "Consumer Electronics Shipment C-219",
    category: "Consumer Electronics",
    owner: companies.vertex,
    buyer: companies.metro,
    supplier: "Helio Components Shenzhen",
    currentStage: "IN_TRANSIT",
    currentValue: 3_180_000,
    originalValue: 3_400_000,
    currency: "INR",
    quantity: 2_400,
    unit: "Cartons",
    location: "Chennai → Mumbai",
    status: "ACTIVE",
    riskLevel: "LOW",
    riskScore: 24,
    financingStatus: "FINANCED",
    financedAmount: 1_800_000,
    availableFinancing: 540_000,
    createdAt: "2026-08-08T05:00:00.000Z",
    lastUpdated: "2026-08-28T06:40:00.000Z",
    situation: "Shipment is on schedule. Eligible for transition from finished-goods to in-transit financing.",
    physical: {
      assetId: "DA-2026-002",
      stage: "IN_TRANSIT",
      location: "NH-48 corridor, near Pune",
      origin: "Chennai CFS",
      destination: "Mumbai Bhiwandi DC",
      quantity: 2_400,
      unit: "Cartons",
      productionCompletion: 100,
      condition: "GOOD",
      verificationStatus: "VERIFIED",
      lastVerifiedAt: "2026-08-28T04:15:00.000Z",
      shipmentStatus: "On schedule · ETA 30 Aug",
    },
    financial: {
      assetId: "DA-2026-002",
      originalValue: 3_400_000,
      currentValue: 3_180_000,
      financedAmount: 1_800_000,
      availableFinancing: 540_000,
      outstandingExposure: 1_800_000,
      currency: "INR",
      financingStatus: "FINANCED",
    },
    contractual: {
      assetId: "DA-2026-002",
      purchaseOrderNumber: "PO-MRI-2026-219",
      buyer: companies.metro,
      supplier: "Helio Components Shenzhen",
      paymentTerms: "Net 45 Days",
      deliveryDate: "2026-08-30",
      contractStatus: "In force",
      ownershipStatus: "In transit · seller until DC scan",
    },
  }),
  twin({
    id: "DA-2026-003",
    name: "Industrial Machinery Components M-778",
    category: "Industrial Equipment",
    owner: companies.titan,
    buyer: companies.globalEng,
    supplier: "ForgeWorks Pune",
    currentStage: "WAREHOUSE",
    currentValue: 5_620_000,
    originalValue: 5_900_000,
    currency: "INR",
    quantity: 86,
    unit: "Assemblies",
    location: "Pune Central Warehouse",
    status: "WATCH",
    riskLevel: "HIGH",
    riskScore: 76,
    financingStatus: "PENDING_REVIEW",
    financedAmount: 3_900_000,
    availableFinancing: 210_000,
    createdAt: "2026-07-22T08:00:00.000Z",
    lastUpdated: "2026-08-28T05:10:00.000Z",
    attention: true,
    situation: "A quantity mismatch was detected between production records and warehouse records.",
    physical: {
      assetId: "DA-2026-003",
      stage: "WAREHOUSE",
      location: "Pune Central Warehouse · Bay 12",
      quantity: 86,
      unit: "Assemblies",
      productionCompletion: 100,
      condition: "WATCH",
      verificationStatus: "MISMATCH",
      lastVerifiedAt: "2026-08-28T05:02:00.000Z",
    },
    financial: {
      assetId: "DA-2026-003",
      originalValue: 5_900_000,
      currentValue: 5_620_000,
      financedAmount: 3_900_000,
      availableFinancing: 210_000,
      outstandingExposure: 3_900_000,
      currency: "INR",
      financingStatus: "PENDING_REVIEW",
    },
    contractual: {
      assetId: "DA-2026-003",
      purchaseOrderNumber: "PO-GEC-2026-778",
      buyer: companies.globalEng,
      supplier: "ForgeWorks Pune",
      paymentTerms: "Net 30 Days after GRN",
      deliveryDate: "2026-09-04",
      contractStatus: "Held pending reconciliation",
      ownershipStatus: "Warehouse receipt · disputed quantity",
    },
  }),
  twin({
    id: "DA-2026-004",
    name: "Solar Panel Manufacturing Order S-341",
    category: "Renewable Energy",
    owner: companies.sungrid,
    buyer: companies.ecopower,
    supplier: "Gujarat Glass & Cell Co.",
    currentStage: "PURCHASE_ORDER",
    currentValue: 7_800_000,
    originalValue: 7_800_000,
    currency: "INR",
    quantity: 4_200,
    unit: "Panels",
    location: "PO desk · Ahmedabad",
    status: "ACTIVE",
    riskLevel: "LOW",
    riskScore: 18,
    financingStatus: "UNFINANCED",
    financedAmount: 0,
    availableFinancing: 4_680_000,
    createdAt: "2026-08-26T09:30:00.000Z",
    lastUpdated: "2026-08-28T04:00:00.000Z",
    situation: "Verified purchase order received and procurement financing opportunity identified.",
    physical: {
      assetId: "DA-2026-004",
      stage: "PURCHASE_ORDER",
      location: "Not yet mobilised",
      quantity: 4_200,
      unit: "Panels",
      productionCompletion: 0,
      condition: "GOOD",
      verificationStatus: "VERIFIED",
      lastVerifiedAt: "2026-08-27T11:00:00.000Z",
    },
    financial: {
      assetId: "DA-2026-004",
      originalValue: 7_800_000,
      currentValue: 7_800_000,
      financedAmount: 0,
      availableFinancing: 4_680_000,
      outstandingExposure: 0,
      currency: "INR",
      financingStatus: "UNFINANCED",
    },
    contractual: {
      assetId: "DA-2026-004",
      purchaseOrderNumber: "PO-ECP-2026-341",
      buyer: companies.ecopower,
      supplier: "Gujarat Glass & Cell Co.",
      paymentTerms: "30% advance · balance Net 45",
      deliveryDate: "2026-10-12",
      contractStatus: "Executed · awaiting procurement",
      ownershipStatus: "Buyer PO committed · title not transferred",
    },
  }),
  twin({
    id: "DA-2026-005",
    name: "Pharmaceutical Raw Materials P-563",
    category: "Pharmaceutical Manufacturing",
    owner: companies.medcore,
    buyer: companies.healthfirst,
    supplier: "Karnataka Fine Chem",
    currentStage: "RAW_MATERIAL",
    currentValue: 1_840_000,
    originalValue: 2_100_000,
    currency: "INR",
    quantity: 12_400,
    unit: "kg",
    location: "Bengaluru Production Facility",
    status: "ACTIVE",
    riskLevel: "MEDIUM",
    riskScore: 38,
    financingStatus: "PARTIAL",
    financedAmount: 900_000,
    availableFinancing: 320_000,
    createdAt: "2026-08-12T07:40:00.000Z",
    lastUpdated: "2026-08-27T18:20:00.000Z",
    situation: "Raw materials verified and ready for production.",
    physical: {
      assetId: "DA-2026-005",
      stage: "RAW_MATERIAL",
      location: "Bengaluru Production Facility · Cold store 2",
      quantity: 12_400,
      unit: "kg",
      productionCompletion: 0,
      condition: "GOOD",
      verificationStatus: "VERIFIED",
      lastVerifiedAt: "2026-08-27T16:40:00.000Z",
    },
    financial: {
      assetId: "DA-2026-005",
      originalValue: 2_100_000,
      currentValue: 1_840_000,
      financedAmount: 900_000,
      availableFinancing: 320_000,
      outstandingExposure: 900_000,
      currency: "INR",
      financingStatus: "PARTIAL",
    },
    contractual: {
      assetId: "DA-2026-005",
      purchaseOrderNumber: "PO-HFP-2026-563",
      buyer: companies.healthfirst,
      supplier: "Karnataka Fine Chem",
      paymentTerms: "Net 30 Days",
      deliveryDate: "2026-09-09",
      contractStatus: "In force",
      ownershipStatus: "MedCore bonded inventory",
    },
  }),
  twin({
    id: "DA-2026-006",
    name: "Textile Export Batch T-912",
    category: "Textile & Apparel",
    owner: companies.heritage,
    buyer: companies.nordic,
    supplier: "Coimbatore Spinning Cluster",
    currentStage: "FINISHED_GOODS",
    currentValue: 2_760_000,
    originalValue: 2_900_000,
    currency: "INR",
    quantity: 18_000,
    unit: "Garments",
    location: "Tiruppur finished-goods bay",
    status: "ACTIVE",
    riskLevel: "LOW",
    riskScore: 27,
    financingStatus: "FINANCED",
    financedAmount: 1_500_000,
    availableFinancing: 650_000,
    createdAt: "2026-07-30T04:20:00.000Z",
    lastUpdated: "2026-08-27T12:00:00.000Z",
    situation: "Goods are completed and awaiting shipment.",
    physical: {
      assetId: "DA-2026-006",
      stage: "FINISHED_GOODS",
      location: "Tiruppur finished-goods bay",
      origin: "Tiruppur",
      destination: "Gothenburg via Chennai Port",
      quantity: 18_000,
      unit: "Garments",
      productionCompletion: 100,
      condition: "GOOD",
      verificationStatus: "VERIFIED",
      lastVerifiedAt: "2026-08-27T11:30:00.000Z",
      shipmentStatus: "Booking confirmed · not yet gated in",
    },
    financial: {
      assetId: "DA-2026-006",
      originalValue: 2_900_000,
      currentValue: 2_760_000,
      financedAmount: 1_500_000,
      availableFinancing: 650_000,
      outstandingExposure: 1_500_000,
      currency: "INR",
      financingStatus: "FINANCED",
    },
    contractual: {
      assetId: "DA-2026-006",
      purchaseOrderNumber: "PO-NRA-2026-912",
      buyer: companies.nordic,
      supplier: "Coimbatore Spinning Cluster",
      paymentTerms: "LC at sight",
      deliveryDate: "2026-09-06",
      contractStatus: "In force",
      ownershipStatus: "Exporter until BL issuance",
    },
  }),
  twin({
    id: "DA-2026-007",
    name: "Food Processing Delivery F-110",
    category: "Food Processing",
    owner: companies.fresh,
    buyer: companies.nationalFood,
    supplier: "Nashik Packhouse",
    currentStage: "RECEIVABLE",
    currentValue: 2_200_000,
    originalValue: 2_450_000,
    currency: "INR",
    quantity: 64,
    unit: "Pallets",
    location: "Buyer DC · Hyderabad",
    status: "ACTIVE",
    riskLevel: "MEDIUM",
    riskScore: 45,
    financingStatus: "FINANCED",
    financedAmount: 1_600_000,
    availableFinancing: 420_000,
    createdAt: "2026-07-18T03:00:00.000Z",
    lastUpdated: "2026-08-27T09:15:00.000Z",
    attention: true,
    situation: "Delivery is confirmed and invoice is issued, but buyer payment is expected in 31 days.",
    physical: {
      assetId: "DA-2026-007",
      stage: "RECEIVABLE",
      location: "National Food DC · Hyderabad",
      quantity: 64,
      unit: "Pallets",
      productionCompletion: 100,
      condition: "GOOD",
      verificationStatus: "VERIFIED",
      lastVerifiedAt: "2026-08-26T14:00:00.000Z",
    },
    financial: {
      assetId: "DA-2026-007",
      originalValue: 2_450_000,
      currentValue: 2_200_000,
      financedAmount: 1_600_000,
      availableFinancing: 420_000,
      outstandingExposure: 1_600_000,
      invoiceValue: 2_450_000,
      currency: "INR",
      financingStatus: "FINANCED",
    },
    contractual: {
      assetId: "DA-2026-007",
      purchaseOrderNumber: "PO-NFD-2026-110",
      buyer: companies.nationalFood,
      supplier: "Nashik Packhouse",
      paymentTerms: "Net 45 Days",
      deliveryDate: "2026-08-26",
      invoiceNumber: "INV-FH-2026-4410",
      invoiceValue: 2_450_000,
      expectedPaymentDate: "2026-09-28",
      contractStatus: "Delivered · receivable open",
      ownershipStatus: "Buyer accepted · seller receivable",
    },
  }),
  twin({
    id: "DA-2026-008",
    name: "Medical Equipment Order H-680",
    category: "Healthcare Equipment",
    owner: companies.caretech,
    buyer: companies.medlife,
    supplier: "CareTech Tooling Unit",
    currentStage: "CASH_REALISED",
    currentValue: 0,
    originalValue: 3_600_000,
    currency: "INR",
    quantity: 12,
    unit: "Systems",
    location: "MedLife Hospitals · settled",
    status: "SETTLED",
    riskLevel: "CLOSED",
    riskScore: 0,
    financingStatus: "SETTLED",
    financedAmount: 0,
    availableFinancing: 0,
    createdAt: "2026-05-04T08:00:00.000Z",
    lastUpdated: "2026-08-21T11:00:00.000Z",
    situation: "Buyer payment was received and the financing lifecycle was successfully settled.",
    physical: {
      assetId: "DA-2026-008",
      stage: "CASH_REALISED",
      location: "Installed at MedLife Hospitals",
      quantity: 12,
      unit: "Systems",
      productionCompletion: 100,
      condition: "SETTLED",
      verificationStatus: "VERIFIED",
      lastVerifiedAt: "2026-08-21T10:40:00.000Z",
    },
    financial: {
      assetId: "DA-2026-008",
      originalValue: 3_600_000,
      currentValue: 0,
      financedAmount: 0,
      availableFinancing: 0,
      outstandingExposure: 0,
      invoiceValue: 3_600_000,
      currency: "INR",
      financingStatus: "SETTLED",
    },
    contractual: {
      assetId: "DA-2026-008",
      purchaseOrderNumber: "PO-MLH-2026-680",
      buyer: companies.medlife,
      supplier: "CareTech Tooling Unit",
      paymentTerms: "Net 30 Days",
      deliveryDate: "2026-07-28",
      invoiceNumber: "INV-CT-2026-680",
      invoiceValue: 3_600_000,
      expectedPaymentDate: "2026-08-20",
      contractStatus: "Closed",
      ownershipStatus: "Transferred · cash realised",
    },
  }),
];

export function getBaseAssetById(id: string): Asset | undefined {
  return baseAssets.find((asset) => asset.id === id);
}
