export const companies = {
  nova: "Nova Manufacturing Pvt. Ltd.",
  apex: "Apex Mobility Ltd.",
  precision: "Precision Metals India",
  vertex: "Vertex Electronics Ltd.",
  metro: "Metro Retail India",
  titan: "Titan Industrial Systems",
  globalEng: "Global Engineering Corp.",
  sungrid: "SunGrid Technologies",
  ecopower: "EcoPower Projects Ltd.",
  medcore: "MedCore Laboratories",
  healthfirst: "HealthFirst Pharma",
  heritage: "Heritage Textiles",
  nordic: "Nordic Retail AB",
  fresh: "FreshHarvest Foods",
  nationalFood: "National Food Distribution Ltd.",
  caretech: "CareTech Manufacturing",
  medlife: "MedLife Hospitals",
  flowCapital: "FlowCapital Working Capital Desk",
} as const;
