import type { LifecycleEvent } from "@/types/event";
import { formatRelativeTime } from "@/lib/format";
import { PRIMARY_ASSET_ID } from "@/lib/demo-data/assets";

const DEMO_NOW = new Date("2026-08-28T07:30:00.000Z");

function event(partial: Omit<LifecycleEvent, "relativeTime">): LifecycleEvent {
  return {
    ...partial,
    relativeTime: formatRelativeTime(partial.timestamp, DEMO_NOW),
  };
}

export const baseEvents: LifecycleEvent[] = [
  event({
    id: "001-e01",
    assetId: PRIMARY_ASSET_ID,
    type: "PO_CREATED",
    stage: "PURCHASE_ORDER",
    title: "Purchase order created",
    description: "Apex Mobility raised PO-APX-2026-0842 for Batch A-452 (18,500 automotive components).",
    timestamp: "2026-08-15T06:10:00.000Z",
    severity: "info",
    category: "contract",
    domain: "physical",
    source: "Purchase Order System",
  }),
  event({
    id: "001-e02",
    assetId: PRIMARY_ASSET_ID,
    type: "PO_VERIFIED",
    stage: "PURCHASE_ORDER",
    title: "Purchase order verified",
    description: "PO terms, quantity, and Net 60 payment schedule were verified against the buyer master.",
    timestamp: "2026-08-16T08:40:00.000Z",
    severity: "success",
    category: "verification",
    domain: "verification",
    source: "Purchase Order System",
    metadata: { confidence: 98 },
  }),
  event({
    id: "001-e03",
    assetId: PRIMARY_ASSET_ID,
    type: "PROCUREMENT_STARTED",
    stage: "PROCUREMENT",
    title: "Procurement initiated",
    description: "Precision Metals India confirmed mill allocation for alloy strip required by Batch A-452.",
    timestamp: "2026-08-18T05:20:00.000Z",
    severity: "info",
    category: "procurement",
    domain: "physical",
    source: "ERP / Procurement",
  }),
  event({
    id: "001-e04",
    assetId: PRIMARY_ASSET_ID,
    type: "PROCUREMENT_COMPLETED",
    stage: "PROCUREMENT",
    title: "Procurement completed",
    description: "Inbound purchase against the PO was closed and goods-in-transit to Chennai was booked.",
    timestamp: "2026-08-20T09:00:00.000Z",
    severity: "success",
    category: "procurement",
    domain: "physical",
    source: "ERP / Procurement",
  }),
  event({
    id: "001-e05",
    assetId: PRIMARY_ASSET_ID,
    type: "RAW_MATERIAL_RECEIVED",
    stage: "RAW_MATERIAL",
    title: "Raw materials verified",
    description: "GRN completed at Chennai Manufacturing Facility. Heat numbers matched the mill certificate.",
    timestamp: "2026-08-22T07:15:00.000Z",
    severity: "success",
    category: "verification",
    domain: "verification",
    source: "ERP / Production System",
  }),
  event({
    id: "001-e06",
    assetId: PRIMARY_ASSET_ID,
    type: "PRODUCTION_STARTED",
    stage: "PRODUCTION",
    title: "Production started",
    description: "Line 3 commenced stamping and machining for Batch A-452.",
    timestamp: "2026-08-24T04:40:00.000Z",
    severity: "success",
    category: "production",
    domain: "physical",
    source: "ERP / Production System",
  }),
  event({
    id: "001-e07",
    assetId: PRIMARY_ASSET_ID,
    type: "PRODUCTION_30",
    stage: "PRODUCTION",
    title: "Production reached 30% completion",
    description: "First-pass yield held at 98.4%. WIP value marked to ₹28.6L.",
    timestamp: "2026-08-25T11:20:00.000Z",
    severity: "info",
    category: "production",
    domain: "physical",
    source: "ERP / Production System",
    metadata: { completion: 30 },
  }),
  event({
    id: "001-e08",
    assetId: PRIMARY_ASSET_ID,
    type: "PRODUCTION_50",
    stage: "PRODUCTION",
    title: "Production reached 50%",
    description: "Machining complete on 9,250 units. Assembly cells started overnight shift.",
    timestamp: "2026-08-26T08:05:00.000Z",
    severity: "info",
    category: "production",
    domain: "physical",
    source: "ERP / Production System",
    metadata: { completion: 50 },
  }),
  event({
    id: "001-e09",
    assetId: PRIMARY_ASSET_ID,
    type: "MATERIAL_DELAY",
    stage: "PRODUCTION",
    title: "Raw material delivery delay detected",
    description: "A follow-on alloy strip lot arrived 2 days late, stretching the remaining production window.",
    timestamp: "2026-08-27T06:50:00.000Z",
    severity: "warning",
    category: "production",
    domain: "physical",
    source: "ERP / Production System",
  }),
  event({
    id: "001-e10",
    assetId: PRIMARY_ASSET_ID,
    type: "RISK_RECALCULATED",
    stage: "PRODUCTION",
    title: "Risk score recalculated from 34 to 42",
    description: "Raw-material delivery delay increased production timeline uncertainty.",
    timestamp: "2026-08-27T09:10:00.000Z",
    severity: "warning",
    category: "risk",
    domain: "risk",
    source: "Risk Engine (local)",
    metadata: { from: 34, to: 42 },
  }),
  event({
    id: "001-e11",
    assetId: PRIMARY_ASSET_ID,
    type: "PRODUCTION_65",
    stage: "PRODUCTION",
    title: "Production reached 65%",
    description: "12,025 units cleared in-process QA. Current twin value ₹42.50L.",
    timestamp: "2026-08-28T07:20:00.000Z",
    severity: "success",
    category: "production",
    domain: "physical",
    source: "ERP / Production System",
    metadata: { completion: 65 },
  }),
  event({
    id: "002-e01",
    assetId: "DA-2026-002",
    type: "SHIPMENT_DEPARTED",
    stage: "IN_TRANSIT",
    title: "Shipment departed Chennai CFS",
    description: "2,400 cartons gated out. GPS trail attached to the twin.",
    timestamp: "2026-08-27T03:30:00.000Z",
    severity: "success",
    category: "shipment",
    domain: "physical",
    source: "Logistics",
  }),
  event({
    id: "002-e02",
    assetId: "DA-2026-002",
    type: "SHIPMENT_ON_SCHEDULE",
    stage: "IN_TRANSIT",
    title: "Shipment on schedule",
    description: "ETA Mumbai Bhiwandi DC remains 30 Aug. No exception codes.",
    timestamp: "2026-08-28T06:40:00.000Z",
    severity: "info",
    category: "shipment",
    domain: "physical",
    source: "Logistics",
  }),
  event({
    id: "002-e03",
    assetId: "DA-2026-002",
    type: "FINANCING_ELIGIBLE",
    stage: "IN_TRANSIT",
    title: "In-transit financing eligibility confirmed",
    description: "Finished-goods facility can transition; exposure remains inside the approved limit.",
    timestamp: "2026-08-28T06:55:00.000Z",
    severity: "info",
    category: "financing",
    domain: "financial",
    source: "Capital Desk",
  }),
  event({
    id: "003-e01",
    assetId: "DA-2026-003",
    type: "WAREHOUSE_RECEIPT",
    stage: "WAREHOUSE",
    title: "Warehouse receipt posted",
    description: "M-778 landed in Bay 12. Production system reported 92 assemblies.",
    timestamp: "2026-08-26T12:10:00.000Z",
    severity: "info",
    category: "warehouse",
    domain: "physical",
    source: "Warehouse Records",
  }),
  event({
    id: "003-e02",
    assetId: "DA-2026-003",
    type: "QTY_MISMATCH",
    stage: "WAREHOUSE",
    title: "Quantity mismatch detected",
    description: "Warehouse count is 86 assemblies versus 92 on the production close report.",
    timestamp: "2026-08-28T05:02:00.000Z",
    severity: "critical",
    category: "warehouse",
    domain: "verification",
    source: "Warehouse Records",
    metadata: { productionQty: 92, warehouseQty: 86 },
  }),
  event({
    id: "003-e03",
    assetId: "DA-2026-003",
    type: "RISK_SPIKE",
    stage: "WAREHOUSE",
    title: "Risk score recalculated to 76",
    description: "Unreconciled inventory and high leverage triggered a pending-review hold.",
    timestamp: "2026-08-28T05:10:00.000Z",
    severity: "critical",
    category: "risk",
    domain: "risk",
    source: "Risk Engine (local)",
  }),
  event({
    id: "004-e01",
    assetId: "DA-2026-004",
    type: "PO_CREATED",
    stage: "PURCHASE_ORDER",
    title: "Verified purchase order received",
    description: "EcoPower Projects executed PO-ECP-2026-341 for 4,200 solar panels.",
    timestamp: "2026-08-26T09:30:00.000Z",
    severity: "success",
    category: "contract",
    domain: "verification",
    source: "Purchase Order System",
  }),
  event({
    id: "004-e02",
    assetId: "DA-2026-004",
    type: "PO_FINANCE_OPPORTUNITY",
    stage: "PURCHASE_ORDER",
    title: "Procurement financing opportunity identified",
    description: "₹46.80L of unused PO headroom is available against the verified order.",
    timestamp: "2026-08-28T04:00:00.000Z",
    severity: "info",
    category: "financing",
    domain: "financial",
    source: "Capital Desk",
  }),
  event({
    id: "005-e01",
    assetId: "DA-2026-005",
    type: "RM_VERIFIED",
    stage: "RAW_MATERIAL",
    title: "Raw materials verified",
    description: "12,400 kg pharmaceutical intermediates passed QC and are staged for production.",
    timestamp: "2026-08-27T16:40:00.000Z",
    severity: "success",
    category: "verification",
    domain: "verification",
    source: "ERP / Production System",
  }),
  event({
    id: "006-e01",
    assetId: "DA-2026-006",
    type: "FG_READY",
    stage: "FINISHED_GOODS",
    title: "Finished goods packed and sealed",
    description: "Export batch T-912 is complete and awaiting gate-in at Chennai Port.",
    timestamp: "2026-08-27T11:30:00.000Z",
    severity: "success",
    category: "production",
    domain: "physical",
    source: "ERP / Production System",
  }),
  event({
    id: "007-e01",
    assetId: "DA-2026-007",
    type: "DELIVERED",
    stage: "DELIVERED",
    title: "Delivery confirmed",
    description: "64 pallets accepted at National Food DC, Hyderabad.",
    timestamp: "2026-08-26T14:00:00.000Z",
    severity: "success",
    category: "warehouse",
    domain: "physical",
    source: "Logistics",
  }),
  event({
    id: "007-e02",
    assetId: "DA-2026-007",
    type: "INVOICE_ISSUED",
    stage: "INVOICE",
    title: "Invoice generated",
    description: "INV-FH-2026-4410 issued for ₹24.50L. Cash expected 28 Sep (Net 45).",
    timestamp: "2026-08-27T09:15:00.000Z",
    severity: "info",
    category: "invoice",
    domain: "financial",
    source: "ERP / Billing",
  }),
  event({
    id: "008-e01",
    assetId: "DA-2026-008",
    type: "CASH_RECEIVED",
    stage: "CASH_REALISED",
    title: "Buyer payment received",
    description: "MedLife Hospitals settled INV-CT-2026-680 in full. Twin exposure reduced to zero.",
    timestamp: "2026-08-21T10:40:00.000Z",
    severity: "success",
    category: "invoice",
    domain: "financial",
    source: "Bank / Collections",
  }),
  event({
    id: "008-e02",
    assetId: "DA-2026-008",
    type: "FINANCING_SETTLED",
    stage: "CASH_REALISED",
    title: "Financing lifecycle settled",
    description: "All facilities against H-680 were closed. Digital twin marked cash realised.",
    timestamp: "2026-08-21T11:00:00.000Z",
    severity: "success",
    category: "financing",
    domain: "financial",
    source: "Capital Desk",
  }),
];

export function getBaseEventsForAsset(assetId: string): LifecycleEvent[] {
  return baseEvents
    .filter((item) => item.assetId === assetId)
    .sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
}
