import type {
  LenderDashboard,
  ManufacturerDashboard,
  ProductionRequest,
} from "@/types/platform";

/** Frontend fallback when backend API is unreachable — mirrors backend demo_store. */
export const DEMO_REQUEST_ID = "00000000-0000-4000-8000-000000000100";

export const demoProductionRequest: ProductionRequest = {
  id: DEMO_REQUEST_ID,
  request_code: "PR-EB-1000",
  manufacturer_id: "00000000-0000-4000-8000-000000000001",
  manufacturer_name: "VoltRide Mobility Pvt. Ltd.",
  project_name: "Electric Bike Series X — Batch 1000",
  product_name: "VoltRide City E-Bike",
  product_category: "Electric Mobility",
  quantity: 1000,
  expected_selling_value: 12_000_000,
  estimated_production_cost: 8_500_000,
  required_funding_amount: 5_000_000,
  funding_purpose: "Raw material procurement and production working capital",
  expected_start_date: "2026-08-01",
  expected_completion_date: "2026-10-15",
  buyer_name: "UrbanMove Fleet Services",
  purchase_order_reference: "PO-UM-2026-EB1000",
  description: "Manufacture 1,000 electric bikes for UrbanMove fleet deployment.",
  current_stage: "IN_PRODUCTION",
  progress_pct: 58,
  status: "ACTIVE_FINANCING",
  confidence_score: 68,
  risk_level: "MEDIUM",
  verified_value: 4_200_000,
  financeable_value: 1_960_000,
  outstanding_exposure: 2_000_000,
  unclaimed_value: 0,
  open_conflicts: 1,
  document_completeness_pct: 75,
  financing_recommendation: {
    requested_amount: 5_000_000,
    verified_value: 4_200_000,
    financeable_value: 1_960_000,
    outstanding_exposure: 2_000_000,
    unclaimed_value: 0,
    confidence_score: 68,
    risk_level: "MEDIUM",
    recommended_min: 0,
    recommended_max: 784_000,
    maximum_safe: 0,
    confidence_band: "Low confidence",
    reason: "Confidence 68% with open quantity mismatch; partial conditional financing only.",
    required_conditions: ["Resolve warehouse quantity conflict", "Independent verification required"],
    eligibility_status: "NOT_ELIGIBLE",
  },
  stages: [
    { id: "1", stage_code: "PURCHASE_ORDER", stage_name: "Purchase Order", sequence_order: 1, progress_pct: 100, status: "COMPLETED" },
    { id: "2", stage_code: "RAW_MATERIAL", stage_name: "Raw Material", sequence_order: 2, progress_pct: 100, status: "COMPLETED" },
    { id: "3", stage_code: "IN_PRODUCTION", stage_name: "In Production", sequence_order: 4, progress_pct: 58, status: "IN_PROGRESS" },
    { id: "4", stage_code: "FINISHED_GOODS", stage_name: "Finished Goods", sequence_order: 6, progress_pct: 0, status: "PENDING" },
  ],
  collateral: [
    {
      id: "col-1",
      collateral_code: "COL-EB-RM-001",
      asset_name: "Lithium Battery Pack Inventory",
      asset_type: "RAW_MATERIAL",
      quantity: 1000,
      unit: "Units",
      estimated_value: 2_800_000,
      lifecycle_stage: "RAW_MATERIAL",
      location: "VoltRide Bengaluru Plant — Bay 3",
    },
    {
      id: "col-2",
      collateral_code: "COL-EB-WIP-001",
      asset_name: "E-Bike Work-in-Progress",
      asset_type: "INVENTORY",
      quantity: 580,
      unit: "Units",
      estimated_value: 3_480_000,
      lifecycle_stage: "IN_PRODUCTION",
      location: "VoltRide Assembly Line 2",
    },
  ],
  documents: [
    { id: "d1", document_name: "PO_2026_001.pdf", document_type: "PURCHASE_ORDER", verification_status: "VERIFIED", status: "UPLOADED", file_size_bytes: 2516582 },
    { id: "d2", document_name: "GST_certificate.pdf", document_type: "GST_CERTIFICATE", verification_status: "VERIFIED", status: "UPLOADED", file_size_bytes: 1258291 },
    { id: "d3", document_name: "Production_Plan_SeriesX.pdf", document_type: "PRODUCTION_PLAN", verification_status: "VERIFIED", status: "UPLOADED", file_size_bytes: 3145728 },
    { id: "d4", document_name: "invoice_001.pdf", document_type: "INVOICE", verification_status: "PENDING", status: "UPLOADED", file_size_bytes: 911360 },
  ],
  events: [
    { event_code: "MFG-EB-001", event_type: "PRODUCTION_STARTED", description: "Assembly line 2 started", severity: "info", timestamp: "2026-08-18T06:00:00Z" },
    { event_code: "MFG-EB-004", event_type: "QUANTITY_MISMATCH_DETECTED", description: "Expected 1000; warehouse shows 920", severity: "warning", timestamp: "2026-08-28T05:02:00Z" },
  ],
  conflicts: [
    {
      conflict_code: "CFL-EB-QTY-001",
      conflict_type: "QUANTITY_MISMATCH",
      severity: "HIGH",
      status: "OPEN",
      description: "80-unit discrepancy between production plan and warehouse count.",
      expected_value: "1000",
      actual_value: "920",
    },
  ],
  decisions: [
    {
      id: "dec-1",
      lender_id: "00000000-0000-4000-8000-000000000002",
      lender_name: "Apex Capital Partners",
      decision_type: "CONDITIONALLY_APPROVE",
      requested_amount: 5_000_000,
      approved_amount: 2_000_000,
      instrument: "PRODUCTION_FINANCING",
      reason: "Confidence below full threshold.",
      conditions: ["Independent warehouse verification required"],
      decided_at: "2026-08-20T10:00:00Z",
    },
  ],
  tranches: [
    { id: "tr-1", tranche_code: "TR-EB-001", approved_amount: 2_000_000, outstanding_amount: 2_000_000, instrument: "PRODUCTION_FINANCING", status: "ACTIVE" },
  ],
  capital_forecast: {
    estimated_amount: 1_400_000,
    estimated_days: 6,
    label: "FORECAST / SIMULATION",
    summary: "Estimated funding gap: ₹14L in approximately 6 days.",
  },
};

export const demoManufacturerDashboard: ManufacturerDashboard = {
  active_production_requests: 1,
  total_funding_requested: 5_000_000,
  approved_financing: 2_000_000,
  available_financing_capacity: 0,
  capital_blocked: 2_000_000,
  average_confidence_score: 68,
  open_risks: 1,
  open_conflicts: 1,
  production_progress_pct: 58,
  upcoming_funding_needs: [demoProductionRequest.capital_forecast!],
  requests: [demoProductionRequest],
};

export const demoLenderDashboard: LenderDashboard = {
  available_opportunities: 0,
  requests_under_review: 1,
  total_active_exposure: 2_000_000,
  total_approved_financing: 2_000_000,
  average_portfolio_confidence: 68,
  high_risk_exposures: 1,
  assets_requiring_attention: 1,
  top_up_opportunities: 0,
  step_down_risks: 1,
  blocked_opportunities: 0,
  opportunities: [
    {
      id: DEMO_REQUEST_ID,
      request_code: "PR-EB-1000",
      manufacturer_name: "VoltRide Mobility Pvt. Ltd.",
      project_name: demoProductionRequest.project_name,
      product_name: demoProductionRequest.product_name,
      quantity: 1000,
      current_stage: "IN_PRODUCTION",
      requested_funding: 5_000_000,
      verified_value: 4_200_000,
      confidence_score: 68,
      risk_level: "MEDIUM",
      financeable_value: 1_960_000,
      outstanding_exposure: 2_000_000,
      unclaimed_value: 0,
      funding_readiness: "CONDITIONAL",
      open_conflicts: 1,
      document_completeness_pct: 75,
      recommended_min: 0,
      recommended_max: 784_000,
      eligibility_status: "NOT_ELIGIBLE",
      status: "ACTIVE_FINANCING",
    },
  ],
};
